Pull request para teste
jeanvarela/construcao pull request #8
Opened 2022-03-02 20:28 UTC by jeanv1

2022-03-02 20:30 UTC, jeanvarela requested changes

2022-03-02 20:30 UTC, jeanvarela commented on src/main/java/br/com/util/configuracao/ConfiguracaoProperties.java
> +//   @Value("${PORT_MICROSERVICE_AUTENTICACAO}")
Remover comentários não utilizados

2022-03-02 20:31 UTC, jeanv1 commented on src/main/java/br/com/util/configuracao/ConfiguracaoProperties.java
> +//   @Value("${PORT_MICROSERVICE_AUTENTICACAO}")
Resolvido

2022-03-04 12:50 UTC, jeanvarela approved these changes

2023-09-14 13:30 UTC, closed without merging